### ISSUE TITLE
Release initial version

### ISSUE THREAD

**Issue by jpsamaroo** [iovisor/ubpf#47]
I'd like to start depending on ubpf for my [BPFnative](https://github.com/jpsamaroo/BPFnative.jl) library. I can make up arbitrary versions for ubpf, but I would prefer not to. It would be great if a version 0.1 (or 0.0.1) could be released, and then we follow Semver or similar and cut regular releases.

**Comment by pchaigno** [comment]
I have mixed feelings about this because I think making a release would signal a willingness to maintain it (ensure it's stability and compatibility with other versions). I don't think ubpf is there yet.

I'm also unsure I understand the use case. You mention you prefer not to make up arbitrary versions for ubpf. If we make a release now, how would it not be arbitrary? Do you have an idea in mind to select which commit to make into a release? Or maybe there is a technical reason why you would prefer to have an official release in ubpf?

**Comment by jpsamaroo** [comment]
That's fair. My use case is packaging ubpf via Julia's BinaryBuilder platform, which requires you to specify a package version (like most distribution systems). I ended up just forking ubpf and choosing release numbers arbitrarily, but once ubpf is more mature and ready for releases, I'll switch the build script back to this repo.

I'm closing this because you're right, we're not there yet :slightly_smiling_face:
